const fs = require('fs');

const campusesData = JSON.parse(fs.readFileSync('src/data/campuses.json', 'utf8'));

function normalize(str) {
    if (!str) return '';
    return str.toLocaleLowerCase('tr-TR').replace(/['"]/g, '').trim();
}

let newCampusesCreated = 0;

for (let uni of Object.values(campusesData)) {
    let campusesCopy = [...(uni.campuses || [])];
    for (let c of campusesCopy) {
        if (!c.autoGenerated) {
            let validUnits = [];
            let invalidUnits = [];
            
            // Extract from academicUnits
            (c.academicUnits || []).forEach(u => {
                let isMyo = u.name.toUpperCase().includes("MYO") || u.name.toUpperCase().includes("MESLEK YÜKSEK");
                if (isMyo) {
                    let cleanCampus = normalize(c.name).replace(' yerleşkesi', '').replace(' kampüsü', '').replace('myo', '').trim();
                    let words = cleanCampus.split(' ').filter(w => w.length > 3);
                    let matched = false;
                    for (let w of words) { if (normalize(u.name).includes(w)) matched = true; }
                    
                    if (matched) validUnits.push(u);
                    else invalidUnits.push(u);
                } else {
                    validUnits.push(u);
                }
            });
            c.academicUnits = validUnits;
            
            // Also extract from unitNames!!
            let validUnitNames = [];
            (c.unitNames || []).forEach(uName => {
                let isMyo = uName.toUpperCase().includes("MYO") || uName.toUpperCase().includes("MESLEK YÜKSEK");
                if (isMyo) {
                    let cleanCampus = normalize(c.name).replace(' yerleşkesi', '').replace(' kampüsü', '').replace('myo', '').trim();
                    let words = cleanCampus.split(' ').filter(w => w.length > 3);
                    let matched = false;
                    for (let w of words) { if (normalize(uName).includes(w)) matched = true; }
                    
                    if (matched) validUnitNames.push(uName);
                    else {
                        // Check if it's already in invalidUnits to avoid duplicates
                        if (!invalidUnits.find(u => normalize(u.name) === normalize(uName))) {
                            invalidUnits.push({ name: uName, type: "MYO", programs: [] });
                        }
                    }
                } else {
                    validUnitNames.push(uName);
                }
            });
            c.unitNames = validUnitNames;
            
            invalidUnits.forEach(u => {
                let campusName = u.name;
                if (u.name.toUpperCase().includes("MESLEK YÜKSEKOKULU")) {
                     campusName = u.name.toUpperCase().replace("MESLEK YÜKSEKOKULU", "Yerleşkesi (MYO)").trim();
                } else if (u.name.toUpperCase().includes("MYO")) {
                     campusName = u.name.toUpperCase().replace("MYO", "Yerleşkesi (MYO)").trim();
                } else {
                     campusName = u.name + " Yerleşkesi";
                }
                
                let lat = c.latitude + (Math.random() - 0.5) * 0.02;
                let lon = c.longitude + (Math.random() - 0.5) * 0.02;
                
                uni.campuses.push({
                    id: uni.universityId + "-campus-" + Math.floor(Math.random()*10000000),
                    name: campusName,
                    universityId: uni.universityId,
                    universityName: uni.universityName,
                    city: c.city,
                    isMain: false,
                    autoGenerated: true,
                    latitude: lat,
                    longitude: lon,
                    academicUnits: [u],
                    facultyNames: [u.name] // also add to facultyNames so it matches
                });
                newCampusesCreated++;
            });
        }
    }
}

fs.writeFileSync('src/data/campuses.json', JSON.stringify(campusesData, null, 2));
console.log("Extracted invalid MYOs into standalone campuses:", newCampusesCreated);
