const fs = require('fs');
const https = require('https');

function geocode(query) {
    return new Promise((resolve) => {
        const url = 'https://nominatim.openstreetmap.org/search?format=json&q=' + encodeURIComponent(query);
        const req = https.get(url, { headers: { 'User-Agent': 'UniversiteHaritasiBot/1.0' } }, (res) => {
            let data = '';
            res.on('data', chunk => data += chunk);
            res.on('end', () => {
                try {
                    let json = JSON.parse(data);
                    if (json && json.length > 0) resolve({ lat: parseFloat(json[0].lat), lon: parseFloat(json[0].lon) });
                    else resolve(null);
                } catch(e) { resolve(null); }
            });
        });
        req.on('error', () => resolve(null));
    });
}

(async () => {
    console.log("Loading data...");
    const progs = JSON.parse(fs.readFileSync('src/data/programs-with-rank.json', 'utf8'));
    const campuses = JSON.parse(fs.readFileSync('src/data/campuses.json', 'utf8'));

    // Clean up previous auto-generated ones and clear academicUnits
    for (let uniKey in campuses) {
        let uni = campuses[uniKey];
        uni.campuses = uni.campuses.filter(c => !(c.autoGenerated && c.id.includes("-campus-")));
        uni.campuses.forEach(c => c.academicUnits = []);
    }

    const uniProgs = {};
    progs.forEach(p => {
        let uni = (p.placementUniversityName || p.universityName || p.university || '').trim().toUpperCase();
        let fac = (p.faculty || 'BİLİNMEYEN BİRİM').trim().toUpperCase();
        if (!uniProgs[uni]) uniProgs[uni] = {};
        if (!uniProgs[uni][fac]) uniProgs[uni][fac] = [];
        
        let unitType = "Birim";
        if (fac.includes("MESLEK YÜKSEK")) unitType = "MYO";
        else if (fac.includes("YÜKSEKOKUL")) unitType = "Yüksekokul";
        else if (fac.includes("FAKÜLTE")) unitType = "Fakülte";
        else if (fac.includes("ENSTİTÜ")) unitType = "Enstitü";
        else if (fac.includes("KONSERVATUVAR")) unitType = "Konservatuvar";
        
        uniProgs[uni][fac].push({
           name: p.name ? p.name.trim() : '',
           degree: p.duration === "2" ? "Önlisans" : "Lisans",
           unitType: unitType
        });
    });

    let geocodeCount = 0;

    for (let uniKey in campuses) {
        let uni = campuses[uniKey];
        let programsMap = uniProgs[(uni.universityName || '').toUpperCase()] || {};
        let unassignedFaculties = Object.keys(programsMap);
        
        uni.campuses.forEach(c => {
           let matchedFaculties = [];
           unassignedFaculties.forEach(fName => {
               let matched = false;
               if ((c.facultyNames && c.facultyNames.includes(fName)) || (c.unitNames && c.unitNames.includes(fName))) {
                   matched = true;
               }
               if (!matched) {
                   let cleanCampus = c.name.toUpperCase().replace(' YERLEŞKESİ', '').replace(' KAMPÜSÜ', '').replace('MYO', '').trim();
                   let words = cleanCampus.split(' ').filter(w => w.length > 3);
                   for (let w of words) {
                       if (fName.includes(w)) { matched = true; break; }
                   }
               }
               if (matched) {
                   matchedFaculties.push(fName);
                   c.academicUnits.push({
                       name: fName,
                       type: programsMap[fName][0]?.unitType || "Birim",
                       programs: programsMap[fName]
                   });
               }
           });
           unassignedFaculties = unassignedFaculties.filter(f => !matchedFaculties.includes(f));
        });
        
        // For unassigned, try to geocode
        for (let fName of unassignedFaculties) {
            let campusName = fName;
            if (fName.includes("MESLEK YÜKSEKOKULU")) {
                 campusName = fName.replace("MESLEK YÜKSEKOKULU", "Yerleşkesi (MYO)").trim();
            } else {
                 campusName = fName + " Yerleşkesi";
            }
            
            let coords = null;
            
            // 1. Precise geocode: University Name + Unit Name
            let query1 = uni.universityName + " " + fName;
            coords = await geocode(query1);
            await new Promise(r => setTimeout(r, 1000)); // strict 1s delay for Nominatim
            geocodeCount++;

            // 2. Fallback geocode: Unit Name + City
            if (!coords) {
                let mainCampus = uni.campuses.find(c => c.isMain);
                let city = mainCampus ? mainCampus.city : "";
                let query2 = fName + (city ? " " + city : "");
                coords = await geocode(query2);
                await new Promise(r => setTimeout(r, 1000));
                geocodeCount++;
            }

            // 3. Fallback to main campus only if it's a Fakülte/Enstitü, otherwise don't attach to main
            if (!coords) {
                let mainCampus = uni.campuses.find(c => c.isMain);
                let isMyo = fName.includes("MESLEK YÜKSEK") || fName.includes("YÜKSEKOKUL");
                
                if (mainCampus && !isMyo) {
                    mainCampus.academicUnits.push({
                        name: fName,
                        type: programsMap[fName][0]?.unitType || "Birim",
                        programs: programsMap[fName]
                    });
                    continue; // Assigned to main
                } else if (mainCampus && isMyo) {
                    // It is an MYO, but we couldn't find its exact building.
                    // We will create a discrete campus, but place it roughly at the district if we can extract it.
                    let district = fName.split(" ")[0];
                    if (district.length > 3) {
                         coords = await geocode(district + " " + mainCampus.city);
                         await new Promise(r => setTimeout(r, 1000));
                    }
                    if (!coords) {
                        // Very last resort offset
                        coords = { lat: mainCampus.latitude + 0.05, lon: mainCampus.longitude + 0.05 };
                    }
                }
            }

            if (coords) {
                let mainCampus = uni.campuses.find(c => c.isMain);
                let newId = uni.universityId + "-campus-" + Math.floor(Math.random()*1000000);
                uni.campuses.push({
                   id: newId,
                   name: campusName,
                   universityId: uni.universityId,
                   universityName: uni.universityName,
                   city: mainCampus ? mainCampus.city : "Türkiye",
                   district: "Merkez", // Can't easily know district
                   address: fName,
                   isMain: false,
                   autoGenerated: true,
                   latitude: coords.lat,
                   longitude: coords.lon,
                   academicUnits: [{
                       name: fName,
                       type: programsMap[fName][0]?.unitType || "Birim",
                       programs: programsMap[fName]
                   }]
                });
            }
            
            if (geocodeCount % 10 === 0) console.log("Geocoded", geocodeCount, "requests...");
        }
    }

    fs.writeFileSync('src/data/campuses.json', JSON.stringify(campuses, null, 2));
    console.log("Successfully accurately geocoded missing campuses!");
})();
