const fs = require('fs');

const campusesData = JSON.parse(fs.readFileSync('src/data/campuses.json', 'utf8'));
const unis = JSON.parse(fs.readFileSync('src/data/universities.json', 'utf8'));

function normalize(str) {
    if (!str) return '';
    return str.toLocaleLowerCase('tr-TR').replace(/['"]/g, '').trim();
}

let newCampusesCreated = 0;

for (let uni of Object.values(campusesData)) {
    let campusesCopy = [...(uni.campuses || [])];
    for (let c of campusesCopy) {
        if (!c.autoGenerated) {
            let validUnits = [];
            let invalidUnits = [];
            (c.academicUnits || []).forEach(u => {
                let isMyo = u.name.toUpperCase().includes("MYO") || u.name.toUpperCase().includes("MESLEK YÜKSEK");
                if (isMyo) {
                    let cleanCampus = normalize(c.name).replace(' yerleşkesi', '').replace(' kampüsü', '').replace('myo', '').trim();
                    let words = cleanCampus.split(' ').filter(w => w.length > 3);
                    let matched = false;
                    for (let w of words) { if (normalize(u.name).includes(w)) matched = true; }
                    
                    // Also check if explicitly in unitNames
                    if (c.unitNames && c.unitNames.map(normalize).includes(normalize(u.name))) matched = true;
                    
                    if (matched) validUnits.push(u);
                    else invalidUnits.push(u);
                } else {
                    validUnits.push(u);
                }
            });
            c.academicUnits = validUnits;
            
            invalidUnits.forEach(u => {
                let campusName = u.name;
                if (u.name.toUpperCase().includes("MESLEK YÜKSEKOKULU")) {
                     campusName = u.name.toUpperCase().replace("MESLEK YÜKSEKOKULU", "Yerleşkesi (MYO)").trim();
                } else if (u.name.toUpperCase().includes("MYO")) {
                     campusName = u.name.toUpperCase().replace("MYO", "Yerleşkesi (MYO)").trim();
                } else {
                     campusName = u.name + " Yerleşkesi";
                }
                
                let lat = c.latitude + (Math.random() - 0.5) * 0.02;
                let lon = c.longitude + (Math.random() - 0.5) * 0.02;
                
                uni.campuses.push({
                    id: uni.universityId + "-campus-" + Math.floor(Math.random()*10000000),
                    name: campusName,
                    universityId: uni.universityId,
                    universityName: uni.universityName,
                    city: c.city,
                    isMain: false,
                    autoGenerated: true,
                    latitude: lat,
                    longitude: lon,
                    academicUnits: [u],
                    facultyNames: [u.name]
                });
                newCampusesCreated++;
            });
        }
    }
}

console.log("Extracted invalid MYOs into standalone campuses:", newCampusesCreated);

// Now re-link public/programs/*.json
function getCampusGroupNames(campus) {
    let extraUnits = [];
    if (campus?.academicUnits) extraUnits = campus.academicUnits.map(u => u.name);
    return [
      ...(Array.isArray(campus?.facultyNames) ? campus.facultyNames : []),
      ...(Array.isArray(campus?.unitNames) ? campus.unitNames : []),
      ...(Array.isArray(campus?.unitAliases) ? campus.unitAliases : []),
      ...extraUnits
    ].map(n => normalize(n));
}

let relinkedCount = 0;
const campusesByUniName = {};
Object.values(campusesData).forEach(u => {
    campusesByUniName[normalize(u.universityName)] = u.campuses || [];
});

const files = fs.readdirSync('public/programs').filter(f => f.endsWith('.json'));

for (let file of files) {
    let progs = JSON.parse(fs.readFileSync('public/programs/' + file, 'utf8'));
    let uniId = parseInt(file.replace('.json', ''));
    let uni = unis.find(u => u.id === uniId);
    if (!uni) continue;
    
    let key = normalize(uni.name);
    let uniCampuses = campusesByUniName[key] || [];
    let isModified = false;
    
    progs.forEach(p => {
        let fac = normalize(p.faculty || p.birimAdi || 'BİLİNMEYEN BİRİM');
        let matchedCampus = null;
        
        for (let c of uniCampuses) {
            if (getCampusGroupNames(c).includes(fac)) { matchedCampus = c; break; }
        }
        
        if (!matchedCampus) {
            for (let c of uniCampuses) {
                let cleanCampus = normalize(c.name).replace(' yerleşkesi', '').replace(' kampüsü', '').replace('myo', '').trim();
                let words = cleanCampus.split(' ').filter(w => w.length > 3);
                for (let w of words) {
                    if (fac.includes(w)) { matchedCampus = c; break; }
                }
                if (matchedCampus) break;
            }
        }
        
        // Final fallback: CREATE one if completely unseen
        if (!matchedCampus) {
            let campusName = (p.faculty || p.birimAdi || 'BİLİNMEYEN BİRİM');
            if (campusName.toUpperCase().includes("MESLEK YÜKSEKOKULU")) {
                 campusName = campusName.toUpperCase().replace("MESLEK YÜKSEKOKULU", "Yerleşkesi (MYO)").trim();
            } else if (!campusName.toUpperCase().includes("YERLEŞKE") && !campusName.toUpperCase().includes("KAMPÜS")) {
                 campusName = campusName + " Yerleşkesi";
            }
            
            let mainCampus = uniCampuses.find(c => c.isMain) || uniCampuses[0];
            let lat = mainCampus ? mainCampus.latitude + (Math.random() - 0.5) * 0.02 : uni.latitude;
            let lon = mainCampus ? mainCampus.longitude + (Math.random() - 0.5) * 0.02 : uni.longitude;
            
            matchedCampus = {
                id: uniId + "-campus-" + Math.floor(Math.random()*10000000),
                name: campusName,
                universityId: uniId.toString(),
                universityName: uni.name,
                city: mainCampus ? mainCampus.city : uni.city,
                isMain: false,
                autoGenerated: true,
                latitude: lat,
                longitude: lon,
                academicUnits: [{
                    name: p.faculty || p.birimAdi,
                    type: campusName.includes("MYO") ? "MYO" : "Fakülte",
                    programs: []
                }],
                facultyNames: [p.faculty || p.birimAdi]
            };
            uniCampuses.push(matchedCampus);
            
            let uniRef = Object.values(campusesData).find(u => normalize(u.universityName) === key);
            if (uniRef) uniRef.campuses.push(matchedCampus);
            
            newCampusesCreated++;
        }
        
        if (p.campus_id !== matchedCampus.id || p.campus_name !== matchedCampus.name) {
            p.campus_id = matchedCampus.id;
            p.campus_name = matchedCampus.name;
            isModified = true;
            relinkedCount++;
        }
    });
    
    if (isModified) {
        fs.writeFileSync('public/programs/' + file, JSON.stringify(progs, null, 2));
    }
}

fs.writeFileSync('src/data/campuses.json', JSON.stringify(campusesData, null, 2));
console.log("Total NEW distinct campuses extracted/created:", newCampusesCreated);
console.log("Programs securely updated away from wrong main campuses:", relinkedCount);
